// constants/action-types.js
export enum ActionTypes {
  FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST",
  FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE",
  FETCH_SELECTED_PRODUCT = "FETCH_SELECTED_PRODUCT",
  FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE",
  CLEAR_SELECTED_PRODUCT = "CLEAR_SELECTED_PRODUCT",
}
